# Generated by Django 3.1.2 on 2021-11-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211128_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
