# Generated by Django 3.1.2 on 2021-11-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211130_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='content',
        ),
    ]
