# Generated by Django 3.1.2 on 2022-01-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(default='Annonymous', max_length=255, null=True),
        ),
    ]
